### ISSUE TITLE
Do you have plan to open the source code of xjsfl.dll?

### ISSUE THREAD

**Issue by jinkim-ea** [davestewart/xjsfl#17] opened 2017-09-18 06:27 UTC
Hi,

I'm a newbie for xjsfl. I have to write some flash extension and found this, xjsfl. I'm interested in using xjsfl and also want to know more detail of internal. I've just started to review xjsfl but have curious for xjsfl.dll.

Do you have plan to open the source code of xjsfl.dll? If you do, I think it'll help me to understand internal of xjsfl more.

Thanks,
JinSan

**Comment by zlumer** [comment] 2017-09-18 06:56
This is a duplicate of #16

**Comment by jinkim-ea** [comment] 2017-09-18 09:04
Oops, sorry. I think I don't post the previous one #16.

Thanks,
JinSan

**Closed** 2017-09-18 09:04 UTC
